services:
  database:
    image: mysql:9.4.0
    container_name: library_db
    environment:
      - MYSQL_ROOT_PASSWORD=admin_password
      - MYSQL_USER=library_admin
      - MYSQL_PASSWORD=library_password
      - MYSQL_DATABASE=library
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u library_admin -p$$MYSQL_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 25s
    networks:
      - library_network

  library:
    build:
      context: ./Library
      dockerfile: Dockerfile
    image: luxwise/library:latest
    container_name: library
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=library
      - DB_USER=library_admin
      - DB_PASSWORD=library_password
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    networks:
      - library_network
    depends_on:
      database:
        condition: service_healthy
        
  log-worker:
    image: luxwise/log-worker:latest
    container_name: log_worker
    build:
      context: .                 
      dockerfile: ./LogWorker/Dockerfile
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=library
      - DB_USER=library_admin
      - DB_PASSWORD=library_password
      - Logs__WatchPath=/logs
      - Logs__Pattern="*.log"
    volumes:
      - ./logs:/logs              
    depends_on:
      - database

networks:
  library_network:
    driver: bridge
