name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Library
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Library/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/library:latest
            ${{ secrets.DOCKER_USERNAME }}/library:${{ github.sha }}

      - name: Build & Push LogWorker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./LogWorker/Dockerfile
          push: true
          build-args: |
            BUILD_CONFIGURATION=Release
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/log-worker:latest
            ${{ secrets.DOCKER_USERNAME }}/log-worker:${{ github.sha }}
