name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Docker

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Library Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/library_technical_test:latest \
          -f Library/Dockerfile Library

    - name: Push Library Iamge
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/library_technical_test:latest

    - name: Build LogWorker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/logWorker_technical_test:latest .

    - name: Push LogWorker Iamge
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/logWorker_technical_test:latest

